export const TOGGLE_SHOW_IMAGE = "TOGGLE_SHOW_IMAGE";
export const LOAD_HEROES_SUCCESS = "LOAD_HEROES_SUCCESS";
export const CREATE_HERO_SUCCESS = "CREATE_HERO_SUCCESS";
export const UPDATE_HERO_SUCCESS = "UPDATE_HERO_SUCCESS";
